<?php
ob_start();

define('FPDF_FONTPATH', 'includes/font/');
require('includes/fpdf.php');
include 'includes/db_connect.php';

$dept = $_GET['dept'] ?? 'CSE';
$sec = $_GET['sec'] ?? 'A';
$sem = $_GET['sem'] ?? 'III-I';

// HELPER: Acronym
function generateAcronym($string) {
    $string = trim(preg_replace('/\s+/', ' ', $string));
    if(strlen($string) <= 4) return strtoupper($string);
    $words = explode(" ", $string);
    $acronym = "";
    foreach ($words as $w) {
        if (!empty($w)) $acronym .= $w[0];
    }
    return strtoupper($acronym);
}

class PDF extends FPDF {
    var $widths;
    var $aligns;

    // --- TEXT WRAPPING HELPERS ---
    function SetWidths($w) { $this->widths = $w; }
    function SetAligns($a) { $this->aligns = $a; }

    function Row($data, $fill=false) {
        $nb = 0;
        for($i=0; $i<count($data); $i++)
            $nb = max($nb, $this->NbLines($this->widths[$i], $data[$i]));
        $h = 5 * $nb;
        $this->CheckPageBreak($h);
        for($i=0; $i<count($data); $i++) {
            $w = $this->widths[$i];
            $a = isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
            $x = $this->GetX();
            $y = $this->GetY();
            $this->Rect($x, $y, $w, $h);
            $this->MultiCell($w, 5, $data[$i], 0, $a, $fill);
            $this->SetXY($x + $w, $y);
        }
        $this->Ln($h);
    }

    function CheckPageBreak($h) {
        if($this->GetY() + $h > $this->PageBreakTrigger)
            $this->AddPage($this->CurOrientation);
    }

    function NbLines($w, $txt) {
        $cw = &$this->CurrentFont['cw'];
        if($w == 0) $w = $this->w - $this->rMargin - $this->x;
        $wmax = ($w - 2 * $this->cMargin) * 1000 / $this->FontSize;
        $s = str_replace("\r", '', $txt);
        $nb = strlen($s);
        if($nb > 0 && $s[$nb-1] == "\n") $nb--;
        $sep = -1;
        $i = 0;
        $j = 0;
        $l = 0;
        $nl = 1;
        while($i < $nb) {
            $c = $s[$i];
            if($c == "\n") { $i++; $sep = -1; $j = $i; $l = 0; $nl++; continue; }
            if($c == ' ') $sep = $i;
            $l += $cw[$c];
            if($l > $wmax) {
                if($sep == -1) { if($i == $j) $i++; } else $i = $sep + 1;
                $sep = -1; $j = $i; $l = 0; $nl++;
            } else $i++;
        }
        return $nl;
    }

    // --- PURE IMAGE HEADER ---
    function Header() {
        
        // 1. IMAGE ONLY
        // We look for 'header.jpg' (or logo.jpeg)
        $img = '';
        if(file_exists('images/header.jpg')) $img = 'images/header.jpg';
        elseif(file_exists('images/logo.jpeg')) $img = 'images/logo.jpeg';

        if($img) {
            // X=15, Y=5. 
            // Width=267 (Full Printable Width of A4 Landscape). Height=Auto.
            $this->Image($img, 15, 5, 267, 0); 
            
            // *** IMPORTANT: VERTICAL SPACE ***
            // This moves the invisible cursor down so the text doesn't overlap the image.
            // If the image covers the text, INCREASE this number (e.g., 40, 45).
            // If there is too much white space, DECREASE this number (e.g., 25, 30).
            $this->Ln(35); 
        } else {
            // Fallback
            $this->SetFont('Arial', 'B', 20);
            $this->Cell(0, 10, 'HEADER IMAGE MISSING', 0, 1, 'C');
            $this->Ln(10);
        }

        // 2. CONTEXT LINE (Dept & Section)
        // We keep this because the image might not say "Section A"
        $this->SetFont('Arial', 'B', 12);
        $this->SetTextColor(0);
        
        $info = "B.Tech " . $GLOBALS['sem'] . "   |   Department: " . $GLOBALS['dept'] . "   |   Section: " . $GLOBALS['sec'];
        $this->Cell(0, 8, $info, 0, 1, 'C');

        // 3. TABLE HEADER
        $this->Ln(2); 
        $this->SetFont('Arial', 'B', 9); 
        $this->SetFillColor(50, 50, 50);
        $this->SetTextColor(255);

        $w_day = 25;
        $w_gap = 6;
        $w_slot = 32; 
        
        $this->Cell($w_day, 8, 'Day', 1, 0, 'C', true);
        $this->Cell($w_slot, 8, '09:20-10:10', 1, 0, 'C', true);
        $this->Cell($w_slot, 8, '10:10-11:00', 1, 0, 'C', true);
        $this->Cell($w_gap, 8, 'Brk', 1, 0, 'C', true);
        $this->Cell($w_slot, 8, '11:20-12:10', 1, 0, 'C', true);
        $this->Cell($w_slot, 8, '12:10-01:00', 1, 0, 'C', true);
        $this->Cell($w_gap, 8, 'Lnh', 1, 0, 'C', true);
        $this->Cell($w_slot, 8, '01:50-02:40', 1, 0, 'C', true);
        $this->Cell($w_slot, 8, '02:40-03:30', 1, 0, 'C', true);
        $this->Cell($w_slot, 8, '03:30-04:20', 1, 1, 'C', true);
    } 

    function Footer() {
        $this->SetY(-10); 
        $this->SetFont('Arial', 'I', 7); 
        $this->SetTextColor(100);
        $this->Cell(0, 10, 'Generated by Timetable System | Page ' . $this->PageNo(), 0, 0, 'C');
    } 
} 

$pdf = new PDF('L', 'mm', 'A4');
$pdf->SetMargins(15, 10, 15); 
$pdf->SetAutoPageBreak(false);
$pdf->AddPage();

// --- 1. THE GRID ---
$days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
$w_day = 25;
$w_gap = 6;
$w_slot = 32;
$h_row = 10; 

foreach ($days as $day) {
    $pdf->SetFont('Arial', 'B', 9);
    $pdf->SetTextColor(0);
    $pdf->SetFillColor(240); 
    $pdf->Cell($w_day, $h_row, $day, 1, 0, 'C', true);
    
    $pdf->SetFont('Arial', '', 9);

    for ($i = 1; $i <= 7; $i++) {
        if ($i == 3 || $i == 5) {
            $pdf->SetFillColor(220);
            $pdf->Cell($w_gap, $h_row, '', 1, 0, 'C', true);
        }

        $sql = "SELECT s.subject_name, s.course_type 
                FROM generated_timetable t
                JOIN subjects s ON t.subject_code = s.subject_code
                WHERE t.day='$day' AND t.slot_id='$i' 
                AND s.department='$dept' AND t.section='$sec' AND s.semester='$sem'";
        
        $res = $conn->query($sql);
        $text = "-";
        $fill = false;

        if ($res->num_rows > 0) {
            $row = $res->fetch_assoc();
            $text = generateAcronym($row['subject_name']); 
            if ($row['course_type'] == 'LAB') {
                $pdf->SetFillColor(200, 230, 255); 
                $fill = true;
            }
        } else {
            $pdf->SetFillColor(255);
        }

        $pdf->Cell($w_slot, $h_row, $text, 1, 0, 'C', $fill);
    } 
    $pdf->Ln();
}

// --- 2. LEGEND (Wrapped) ---
$pdf->Ln(4);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(0, 6, "Subject & Faculty Details", 0, 1, 'L');

$pdf->SetWidths(array(20, 20, 117, 90, 20));
$pdf->SetAligns(array('C', 'C', 'L', 'L', 'C'));

// Legend Header
$pdf->SetFont('Arial', 'B', 8);
$pdf->SetFillColor(230);
$pdf->SetTextColor(0);
$pdf->Cell(20, 6, 'Code', 1, 0, 'C', true);
$pdf->Cell(20, 6, 'Short', 1, 0, 'C', true);
$pdf->Cell(117, 6, 'Subject Name', 1, 0, 'L', true);
$pdf->Cell(90, 6, 'Faculty Name', 1, 0, 'L', true);
$pdf->Cell(20, 6, 'Type', 1, 1, 'C', true);
$pdf->Ln();

// Legend Data
$pdf->SetFont('Arial', '', 8);
$sql_legend = "SELECT s.subject_code, s.subject_name, s.course_type, f.faculty_name 
               FROM course_allotment ca
               JOIN subjects s ON ca.subject_code = s.subject_code
               JOIN faculty f ON ca.faculty_id = f.faculty_id
               WHERE s.department = '$dept' AND ca.section = '$sec' AND s.semester = '$sem'
               ORDER BY s.course_type DESC, s.subject_name";

$res_legend = $conn->query($sql_legend);
while($row = $res_legend->fetch_assoc()) {
    $pdf->Row(array(
        $row['subject_code'], 
        generateAcronym($row['subject_name']), 
        $row['subject_name'], 
        $row['faculty_name'], 
        $row['course_type']
    ));
}

// --- 3. SIGNATURES ---
if ($pdf->GetY() > 175) {
    $pdf->AddPage();
}

$pdf->Ln(15); 
$pdf->SetFont('Arial', 'B', 10);
$pdf->SetTextColor(0);

$pdf->Cell(100, 10, 'HEAD OF DEPARTMENT', 0, 0, 'L');
$pdf->Cell(0, 10, 'PRINCIPAL', 0, 1, 'R');

ob_end_flush();
$filename = "Timetable_{$dept}_{$sem}_{$sec}.pdf";
$pdf->Output('D', $filename);
?>